/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d9dadb",
        "secondary-container": "#fe8b72",
        "on-primary-fixed-variant": "#8c1800",
        "on-secondary-fixed-variant": "#7e2b18",
        "error-container": "#ffdad6",
        "inverse-primary": "#ffb4a4",
        "on-primary-fixed": "#3d0600",
        "secondary-fixed-dim": "#ffb4a4",
        "tertiary-fixed-dim": "#60d5f5",
        "surface-container-high": "#e7e8e9",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#004e5e",
        "inverse-on-surface": "#f0f1f2",
        "on-surface": "#191c1d",
        "outline-variant": "#e4beb6",
        "surface-container-low": "#f3f4f5",
        "surface-container-highest": "#e1e3e4",
        "on-error-container": "#93000a",
        "outline": "#8f7069",
        "secondary-fixed": "#ffdad3",
        "tertiary-fixed": "#b0ecff",
        "surface-container": "#edeeef",
        "on-surface-variant": "#5b403a",
        "surface-tint": "#b72301",
        "on-secondary": "#ffffff",
        "secondary": "#9e422d",
        "on-tertiary-fixed": "#001f27",
        "on-tertiary-container": "#002f3a",
        "primary-fixed-dim": "#ffb4a4",
        "surface": "#f8f9fa",
        "on-secondary-fixed": "#3d0600",
        "surface-bright": "#f8f9fa",
        "on-primary": "#ffffff",
        "primary-container": "#ff5733",
        "primary-fixed": "#ffdad3",
        "inverse-surface": "#2e3132",
        "on-secondary-container": "#742412",
        "primary": "#b72301",
        "tertiary": "#00677c",
        "on-primary-container": "#580c00",
        "tertiary-container": "#009fbd",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1d"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem"
      },
      maxWidth: {
        "3xl": "50rem",
      },
    },
  },
  plugins: [],
}
